name: Build Gradle Project

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner (Windows or Linux, depending on your setup)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (if required, specify the Java version needed for your Gradle project)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify JDK distribution (temurin, zulu, adopt, etc.)
          java-version: '17'       # Change this to the Java version your project requires

      # Step 3: Navigate to the 'demo' folder and build the Gradle project
      - name: Build Gradle project
        run: |
          cd demo
          gradlew build  # Use './gradlew build' if on Linux or MacOS
