name: Compile and Run Java

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-run:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner (Windows)

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK (Java Development Kit) on the Windows runner
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Set the Java version you need (e.g., 8, 11, 17, etc.)

      # Compile the Java program
      - name: Compile Java
        run: javac test.java
      
      # Run the compiled Java program
      - name: Run Java
        run: java test
