name: Compile and Run Java

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-run:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner (Windows)

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK (Java Development Kit) on the Windows runner
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Set the Java version you need (e.g., 8, 11, 17, etc.)

    # Compile the Java program and store the .class files in a specific directory
      - name: Compile Java
        run: javac -d D:\builds test.java  # Compiles the Java file and stores the output in D:\builds
      
      # List the files in the build directory to verify the output
      - name: List build directory contents
        run: dir D:\builds  # Lists the contents of D:\builds to verify the compiled files
      
      # Run the compiled Java program from the specific directory
      - name: Run Java
        run: java -cp D:\builds test  # Runs the Java program from the D:\builds directory
