name: Run on Self-Hosted Runner

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner
    
    steps:
      - name: Print the current directory
        run: |
          echo Current Directory:
          pwd  # Prints the current working directory

      - name: List the contents of the current directory
        run: |
          echo Listing Directory Contents:
          dir  # Lists the contents of the current directory
          
  GenerateReport:
    runs-on: self-hosted
    # Define permissions for the job
    permissions: write-all
    steps:
    - name: Checking out code
      uses: actions/checkout@v3
      with:
        repository: procter-gamble/smaRepo
        ref: main
        token: ${{ secrets.GIT_DEMO_ACCESS }}
        path: _work

