# .github/workflows/self-hosted-runner.yml
name: Run on Self-Hosted Runner

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner
    
    steps:
      - name: Print current directory
        run: pwd  # Prints the current working directory

      - name: List contents of the current directory
        run: ls -la  # Lists the contents of the current directory (optional for verification)
        
