# .github/workflows/self-hosted-runner.yml
name: Run on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Specifies that this job should run on a self-hosted runner
    
    steps:
      - name: Print current directory
        run: dir  # Prints the current working directory

      - name: List contents of the current directory
        run: dir  # Lists the contents of the current directory (optional for verification)
        
